### ISSUE TITLE
dosc.rs not up-to-date with 0.15.0; still on 0.13.0

### ISSUE THREAD

**Issue by metalglove** [antimatter15/tesseract-rs#46]
On https://docs.rs/crate/tesseract/0.15.0 the docs warn that the last successful version was built for 0.13.0.

Is this intentional? Did nothing change?

**Comment by ccouzens** [comment]
Hey

Thanks for pointing this out.

Looking at [the logs](https://docs.rs/crate/tesseract/0.15.0/builds/831595)

```
[INFO] [stderr] 5 | use self::tesseract_sys::TessBaseAPIInit5;
```

The issue seems to be around `TessBaseAPIInit5`.

We can see that `TessBaseAPIInit5` is gated by `tesseract_5_2` [here](https://github.com/ccouzens/tesseract-plumbing/blob/340b20caa4f0ea7fd6ab7e90e336b92b1adba5f1/src/tess_base_api.rs#L4), I think the docs.rs CI system is using an older version of the `tesseract` c library. I'll see if we can have the docs.rs CI not use the feature `tesseract_5_2`.

**Comment by ccouzens** [comment]
Because of this change, it has now built

04070d2941a78cbacf4c25ce25240825d41cc1f1

https://docs.rs/tesseract/0.15.1/tesseract/
